eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8904
spring:
  application:
    name: zuult

zuul:
  routes:
    ribbo:
      path: /hi2/**
      serviceId: hi
    feign:
      path: /hello2/**
      serviceId: figntest