eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 7010
spring:
  rabbitmq:                    #本地环境不需要配置mq，但是需要启动mq,Springboot会自动连接本地mq
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: config
  cloud:
    config:
      lable: master
      server:
        git:
          uri: https://gitee.com/eryizhanghh/configfile
          #username:
          #password:
