eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8095
spring:
  application:
    name: trubinet

security:
  basic:
    enabled: false

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


turbine:
  appConfig: figntest,hi,service-ribbon1
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")